# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passenger.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='passenger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpassenger.proto\"7\n\tPassenger\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04male\x18\x02 \x01(\x08\x12\x0e\n\x06idCard\x18\x03 \x01(\t\"=\n\x0fPassengerAddReq\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\npassengers\x18\x02 \x03(\x0b\x32\n.Passenger\" \n\x0fPassengerAddRsp\x12\r\n\x05\x65rrno\x18\x01 \x01(\t\"\x1d\n\x0fPassengerGetReq\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x0fPassengerGetRsp\x12\x1e\n\npassengers\x18\x01 \x03(\x0b\x32\n.Passengerb\x06proto3'
)




_PASSENGER = _descriptor.Descriptor(
  name='Passenger',
  full_name='Passenger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Passenger.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='male', full_name='Passenger.male', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idCard', full_name='Passenger.idCard', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=74,
)


_PASSENGERADDREQ = _descriptor.Descriptor(
  name='PassengerAddReq',
  full_name='PassengerAddReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PassengerAddReq.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='passengers', full_name='PassengerAddReq.passengers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=137,
)


_PASSENGERADDRSP = _descriptor.Descriptor(
  name='PassengerAddRsp',
  full_name='PassengerAddRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='errno', full_name='PassengerAddRsp.errno', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=171,
)


_PASSENGERGETREQ = _descriptor.Descriptor(
  name='PassengerGetReq',
  full_name='PassengerGetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PassengerGetReq.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=202,
)


_PASSENGERGETRSP = _descriptor.Descriptor(
  name='PassengerGetRsp',
  full_name='PassengerGetRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passengers', full_name='PassengerGetRsp.passengers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=253,
)

_PASSENGERADDREQ.fields_by_name['passengers'].message_type = _PASSENGER
_PASSENGERGETRSP.fields_by_name['passengers'].message_type = _PASSENGER
DESCRIPTOR.message_types_by_name['Passenger'] = _PASSENGER
DESCRIPTOR.message_types_by_name['PassengerAddReq'] = _PASSENGERADDREQ
DESCRIPTOR.message_types_by_name['PassengerAddRsp'] = _PASSENGERADDRSP
DESCRIPTOR.message_types_by_name['PassengerGetReq'] = _PASSENGERGETREQ
DESCRIPTOR.message_types_by_name['PassengerGetRsp'] = _PASSENGERGETRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Passenger = _reflection.GeneratedProtocolMessageType('Passenger', (_message.Message,), {
  'DESCRIPTOR' : _PASSENGER,
  '__module__' : 'passenger_pb2'
  # @@protoc_insertion_point(class_scope:Passenger)
  })
_sym_db.RegisterMessage(Passenger)

PassengerAddReq = _reflection.GeneratedProtocolMessageType('PassengerAddReq', (_message.Message,), {
  'DESCRIPTOR' : _PASSENGERADDREQ,
  '__module__' : 'passenger_pb2'
  # @@protoc_insertion_point(class_scope:PassengerAddReq)
  })
_sym_db.RegisterMessage(PassengerAddReq)

PassengerAddRsp = _reflection.GeneratedProtocolMessageType('PassengerAddRsp', (_message.Message,), {
  'DESCRIPTOR' : _PASSENGERADDRSP,
  '__module__' : 'passenger_pb2'
  # @@protoc_insertion_point(class_scope:PassengerAddRsp)
  })
_sym_db.RegisterMessage(PassengerAddRsp)

PassengerGetReq = _reflection.GeneratedProtocolMessageType('PassengerGetReq', (_message.Message,), {
  'DESCRIPTOR' : _PASSENGERGETREQ,
  '__module__' : 'passenger_pb2'
  # @@protoc_insertion_point(class_scope:PassengerGetReq)
  })
_sym_db.RegisterMessage(PassengerGetReq)

PassengerGetRsp = _reflection.GeneratedProtocolMessageType('PassengerGetRsp', (_message.Message,), {
  'DESCRIPTOR' : _PASSENGERGETRSP,
  '__module__' : 'passenger_pb2'
  # @@protoc_insertion_point(class_scope:PassengerGetRsp)
  })
_sym_db.RegisterMessage(PassengerGetRsp)


# @@protoc_insertion_point(module_scope)
